### ISSUE TITLE
実装手順のタスクの整理

### ISSUE THREAD

**Issue by yonedahayato** [yonedahayato/google#18]
# タスク
- [x] colab file のコピー
- [x] 記録保存用 github repository を用意 (User Agent用？)
  - [colab_test](https://github.com/yonedahayato/colab_test)
- [x] colab file の設定
  - [x] github アクセストークン設定
  - [token](https://docs.google.com/document/d/1ijz0Sv-ELLJDRdnpeULJbYR35X-maMBA9ne_HkBDF2s/edit?folder=1UiLitTPIqY5Jg34h2SJTPvvXKxHuhQKM)
- [x] colab file の実行
- [x] 実行の確認

### エラー 01 (2020/01/06)
```
SC.main()
```

```
0.0953778
---------------------------------------------------------------------------
InvalidArgumentException                  Traceback (most recent call last)
<ipython-input-9-529233c86eb2> in <module>()
----> 1 SC.main()

4 frames
<ipython-input-6-e795967f8d31> in main(self)
    201             else:
    202                 self.set_mode("GPU")
--> 203                 self.auto_access(self.access_path_2)
    204                 # 60分ごとにチェック
    205                 time.sleep(3600)

<ipython-input-6-e795967f8d31> in auto_access(self, path)
    121             self.driver.execute_script("window.open()") #make new tab
    122             self.driver.switch_to.window(self.driver.window_handles[-1]) #switch new tab
--> 123             self.driver.get(path)
    124             # ページの要素が全て読み込まれるまで待機
    125             WebDriverWait(self.driver, 60).until(EC.presence_of_all_elements_located)

/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py in get(self, url)
    331         Loads a web page in the current browser session.
    332         """
--> 333         self.execute(Command.GET, {'url': url})
    334 
    335     @property

/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
    319         response = self.command_executor.execute(driver_command, params)
    320         if response:
--> 321             self.error_handler.check_response(response)
    322             response['value'] = self._unwrap_value(
    323                 response.get('value', None))

/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    240                 alert_text = value['alert'].get('text')
    241             raise exception_class(message, screen, stacktrace, alert_text)
--> 242         raise exception_class(message, screen, stacktrace)
    243 
    244     def _value_or_default(self, obj, key, default):

InvalidArgumentException: Message: invalid argument
  (Session info: headless chrome=79.0.3945.79)
```
